Dockerfile.openshift, OWNERS
Add Dockerfile.openshif and owner fiiles required by ART ticket [3029](https://issues.redhat.com/browse/ART-3029)
=> Initial commit to setup downstream repo dockerfile

Dockerfile.openshift
=> fix typo in the dockerfile

Dockerfile.openshift, vendor/modules.txt
=> remove platform specific build and update modules.txt

go.mod, test/e2e/e2e.go, vendor/github.com/golang/glog/LICENSE, vendor/github.com/golang/glog/README, vendor/github.com/golang/glog/glog.go, vendor/github.com/golang/glog/glog_file.go, vendor/github.com/onsi/ginkgo/extensions/table/table.go, vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go, vendor/modules.txt
Fix d/s build error
> RUN CGO_ENABLED=0 GO111MODULE=on go build -a -mod=vendor -o manager main.go
go: inconsistent vendoring in /workspace:
gopkg.in/yaml.v2@v2.3.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
2021-07-07 10:54:09,544 - atomic_reactor.plugins.imagebuilder - INFO -
To ignore the vendor directory, use -mod=readonly or -mod=mod.
To sync the vendor directory, run:
go mod vendor
running 'CGO_ENABLED=0 GO111MODULE=on go build -a -mod=vendor -o manager main.go' failed with exit code 1
2021-07-07 10:54:10,110 - atomic_reactor.plugin - ERROR - Build step plugin imagebuilder failed: image build failed (rc=1): running 'CGO_ENABLED=0 GO111MODULE=on go build -a -mod=vendor -o manager main.go' failed with exit code 1
=> Fix vendor

test/e2e/e2e.go
=> fix some e2e test cases that assumes hardcode namespace.

.github/workflows/metallb_e2e.yml, api/v1beta1/bgppeer_types.go, api/v1beta1/bgppeer_webhook.go, api/v1beta1/bgppeer_webhook_test.go, bundle/manifests/metallb-operator.clusterserviceversion.yaml, bundle/manifests/metallb.io_bgppeers.yaml, config/crd/bases/metallb.io_bgppeers.yaml, config/frr-on-ci/bgpTypeFRR.yaml, config/frr-on-ci/kustomization.yaml, config/rbac/role.yaml, config/samples/demo/metallb.yaml, controllers/metallb_controller.go, controllers/suite_test.go, hack/generate-metallb-manifests.sh, hack/kind-multi-node-cluster-without-registry.sh, main.go, manifests/4.10/metallb-operator.v4.10.0.clusterserviceversion.yaml, pkg/render/metallb_config.go, pkg/render/metallb_configmap.go, pkg/render/metallb_configmap_test.go, pkg/render/testdata/TestRendering/peersRendering, pkg/render/testdata/TestRendering/peersRendering.golden
Aligning to upstream.
This will add the ebgpmultihop field, plus other commits that are upstream only.
=> Bug 2035250: upstream alignement

.github/workflows/general.yml, .github/workflows/metallb_e2e.yml, Makefile, README.md, bin/metallb-operator-with-webhooks.yaml, bin/metallb-operator.yaml, bindata/deployment/frr/metallb-frr.yaml, bindata/deployment/frr/service-monitors.yaml, bindata/deployment/native/metallb.yaml, bindata/deployment/prometheus-operator/prometheus-operator.yaml, bundle/manifests/metallb-operator.clusterserviceversion.yaml, config/manifests/kustomization.yaml, controllers/metallb_controller.go, hack/generate-metallb-manifests.sh, test/e2e/functional/tests/e2e.go, test/e2e/metallb/metallb.go
syncing commits merged to upstream metallb-operator repo between 7.1 to 25.1
=> Bug 2041087: sync with u/s metallb-operator

api/v1beta1/bgppeer_webhook.go
for the same BGP Instance and in the same VRF its not
possible to have two BGP peers even with different remoteASN
For example:
neighbor 192.168.216.10 remote-as 65000
neighbor 192.168.216.10 remote-as 65001
only one of the entries will get applied
=> Bug 2043234: In FRR mode its not possible to have duplicate BGPPeers

api/v1beta1/bgppeer_webhook.go, api/v1beta1/bgppeer_webhook_test.go
Valid holdtime configuration can be 0 or >= 3sec
=> Bug 2051718: Add holdtime webhook validation

Dockerfile.openshift, bundleci.Dockerfile, manifests/metallb-operator.package.yaml, manifests/stable/controller_v1_serviceaccount.yaml, manifests/stable/image-references, manifests/stable/metallb-operator.v4.11.0.clusterserviceversion.yaml, manifests/stable/metallb.io_addresspools.yaml, manifests/stable/metallb.io_bfdprofiles.yaml, manifests/stable/metallb.io_bgppeers.yaml, manifests/stable/metallb.io_metallbs.yaml, manifests/stable/prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, manifests/stable/prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, manifests/stable/speaker_v1_serviceaccount.yaml, manifests/stable/webhook-service_v1_service.yaml
Doing this under "stable" channel since OLM Operator default channel in now "stable".
=> Add 4.11 manifests

.github/workflows/metallb_e2e.yml, Makefile, bin/metallb-operator-with-webhooks.yaml, bin/metallb-operator.yaml, bindata/deployment/frr-with-webhooks/metallb-frr-with-webhooks.yaml, bindata/deployment/native-with-webhooks/metallb-native-with-webhooks.yaml, bindata/deployment/openshift/metallb-openshift.yaml, bundle/manifests/metallb-operator.clusterserviceversion.yaml, bundle/manifests/metallb.io_communities.yaml, config/crd/bases/metallb.io_addresspools.yaml, config/crd/bases/metallb.io_bgpadvertisements.yaml, config/crd/bases/metallb.io_bgppeers.yaml, config/crd/bases/metallb.io_communities.yaml, config/crd/bases/metallb.io_ipaddresspools.yaml, config/crd/bases/metallb.io_l2advertisements.yaml, config/crd/kustomization.yaml, config/metallb_rbac/metallb-frr-with-webhooks.yaml, config/metallb_rbac/metallb-frr.yaml, config/metallb_rbac/metallb-native-with-webhooks.yaml, config/metallb_rbac/metallb-native.yaml, config/metallb_rbac/metallb-openshift.yaml, hack/common.sh, hack/generate-metallb-manifests.sh, hack/generate_ocp_webhook_manifests.sh, manifests/4.11/metallb.io_communities.yaml, manifests/stable/metallb.io_communities.yaml
Bringing community crds downstream
=> Align to upstream - 20042022

.github/workflows/metallb_e2e.yml, bin/metallb-operator.yaml, bundle/manifests/metallb.io_bgppeers.yaml, config/crd/bases/metallb.io_bgppeers.yaml, hack/common.sh, manifests/stable/metallb.io_bgppeers.yaml
Introducing 4 bytes asn support by relaxing the max allowed value
=> Bug 2097701: 4 bytes asn support

bindata/deployment/frr/metallb-frr.yaml, bindata/deployment/frr/service-monitors.yaml, controllers/metallb_controller.go, manifests/4.10/metallb-operator.v4.10.0.clusterserviceversion.yaml
Exposing the metric ports in host within the allowed and registered range
=> Bug 2089179: metrics ports in allowed ranges

manifests/4.11/metallb-operator.v4.11.0.clusterserviceversion.yaml
Signed-off-by: Periyasamy Palanisamy <pepalani@redhat.com>
=> Enable l2adv webhook for 4.11 manifest

.ci-operator.yaml, Dockerfile.openshift, bundle.Dockerfile, manifests/metallb-operator.package.yaml, manifests/stable/image-references, manifests/stable/metallb-operator.clusterserviceversion.yaml
Move to 4.13 all the 4.12 references
=> OCPBUGS-4447: Bump up the version

bindata/deployment/helm/README.md, bindata/deployment/helm/policy/speaker.rego, bindata/deployment/helm/templates/speaker.yaml, bindata/deployment/helm/values.schema.json, bindata/deployment/helm/values.yaml, hack/common.sh, pkg/helm/testdata/ocp-metrics-speaker.golden, pkg/helm/testdata/ocp-speaker.golden, pkg/helm/testdata/vanilla-metrics-speaker.golden
This PR fixes OCPBUGS-8019 by including the bug fix: https://github.com/openshift/metallb/pull/107
=> OCPBUGS-8019: Read the memberlist secret from a file

controllers/metallb_controller.go, test/e2e/functional/tests/e2e.go, test/e2e/metallb/metallb.go
This is a cherry-pick of #174
Had to resolve conflicts with the automated cherry-pick by only deleting tests that don't exist in 4.11.
=> [release-4.11] OCPBUGS-15567: Fix metallb controller error log

OWNERS
Similarly to MetalLB https://github.com/openshift/metallb/pull/130, also removing Mark and Casey as they are not with us anymore.
=> Add Ori to OWNERS

controllers/metallb_controller.go, hack/kind-cluster-with-registry.sh, hack/kind-cluster-without-registry.sh, hack/kind-multi-node-cluster-without-registry.sh, pkg/status/status.go, test/e2e/functional/tests/e2e.go
This PR syncs with upstream MetalLB up until 27/07/2023.
Bringing 6 new commits, including flaky test fix and improved logs.
=> OCPBUGS-15454: Fix flake MetalLB resources should have correct statuses

bundle.Dockerfile, manifests/metallb-operator.package.yaml, manifests/ocpcsv/align.sh, manifests/ocpcsv/bases/metallb-operator.clusterserviceversion.yaml, manifests/ocpcsv/controller-webhook-patch.yaml, manifests/ocpcsv/ocpvariables.yaml, manifests/stable/image-references, manifests/stable/metallb-operator.clusterserviceversion.yaml
Aligning as master now points to 4.15
=> Bump versions to 4.15

test/consts/const.go, test/e2e/functional/e2e_test.go, test/e2e/k8sreporter/reporter.go, test/e2e/validation/validation_test.go
This PR brings the changes to the K8S reporter from upstream.
=> Align with upstream 14 09 2023

.snyk
Skipping vendor, the e2etests and any test file
=> Add a .snyk configuration file

manifests/stable/metallb-operator.clusterserviceversion.yaml
Adding infra labels as per
https://docs.openshift.com/container-platform/4.15/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-annotations-infra_osdk-generating-csvs
=> OCPBUGS-30566: Add infra labels

manifests/stable/metallb-operator.clusterserviceversion.yaml
=> OCPBUGS-33341: Manifests: fix the provider

manifests/stable/metallb-operator.clusterserviceversion.yaml
Cherry-pick from https://github.com/openshift/metallb-operator/pull/223
=> OCPBUGS-33408: Manifests: fix the provider

manifests/stable/metallb.io_bgppeers.yaml
Align BGPPeer with the changes from https://github.com/openshift/metallb-operator/pull/245
=> OpenShift: align CRDs

pkg/helm/frrk8s.go, pkg/helm/frrk8s_test.go
=> OCPBUGS-44269: frr-k8s: apply affinity/resources/classes as the speaker

.github/workflows/ci.yaml, .github/workflows/publish.yaml, controllers/metallb_controller.go, go.mod, go.sum, hack/ocp_run_e2e.sh, manifests/stable/metallb-operator.clusterserviceversion.yaml, pkg/openshift/openshift.go, pkg/openshift/openshift_test.go, pkg/params/params.go, test/e2e/functional/tests/e2e.go, vendor/github.com/Masterminds/semver/.travis.yml, vendor/github.com/Masterminds/semver/CHANGELOG.md, vendor/github.com/Masterminds/semver/LICENSE.txt, vendor/github.com/Masterminds/semver/Makefile, vendor/github.com/Masterminds/semver/README.md, vendor/github.com/Masterminds/semver/appveyor.yml, vendor/github.com/Masterminds/semver/collection.go, vendor/github.com/Masterminds/semver/constraints.go, vendor/github.com/Masterminds/semver/doc.go, vendor/github.com/Masterminds/semver/version.go, vendor/github.com/Masterminds/semver/version_fuzz.go, vendor/modules.txt
Aligning with upstream, bringing the change to run the e2es against an externally deployed frr-k8s
=> Align upstream: 27-1-2025

bundle.Dockerfile, manifests/metallb-operator.package.yaml, manifests/ocpcsv/align.sh, manifests/ocpcsv/bases/metallb-operator.clusterserviceversion.yaml, manifests/ocpcsv/controller-webhook-patch.yaml, manifests/ocpcsv/ocpvariables.yaml, manifests/stable/image-references, manifests/stable/metallb-operator.clusterserviceversion.yaml
**Is this a BUG FIX or a FEATURE ?**:
> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind cleanup
> /kind feature
> /kind design
> /kind flake
> /kind failing
> /kind documentation
> /kind regression
**Special notes for your reviewer**:
**Release note**:
```release-note
```
=> OpenShift Only: align versions to 4.20

go.mod, go.sum, vendor/github.com/golang/glog/glog.go, vendor/github.com/golang/glog/glog_file.go, vendor/github.com/golang/glog/glog_file_nonwindows.go, vendor/github.com/golang/glog/glog_file_windows.go, vendor/modules.txt
=> OCPBUGS-59878: Sync 29725
