openshift/metallb-operator

Dockerfile.openshift
remove nonroot USER not able to test ART operator image I get the following error
```
docker run -it registry-proxy.engineering.redhat.com/rh-osbs/openshift-ose-metallb-operator:rhaos-4.9-rhel-8-containers-hotfix-22228-20210623043520 bash -c "ls -l"
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Error: unable to find user nonroot: no matching entries in passwd file
```
=> remove nonroot user from openshift Dockerfile

manifests/4.9/metallb-operator.v4.9.0.clusterserviceversion.yaml
The OperatorHub currently assumes x86-only for any operators which do
not declare any such labels.  Declaring these explicitly should make the
current status more obvious in the code, and make it easier to correctly
add further architectures when conditions warrant.
=> Bug 1987136: Declare supported arches in CSV

manifests/4.9/metallb-operator.v4.9.0.clusterserviceversion.yaml
Update manifest's MetalLB namespace
=> Bug 1991316: Update MetalLB CSV namespace to start with openshift prefix

manifests/4.9/metallb-operator.v4.9.0.clusterserviceversion.yaml, manifests/art.yaml
The skipRange replacement has been a no-op. This change makes it
effective.
=> Bug 1994979: Fix olm.skipRange replacements

bundle/manifests/metallb-operator.clusterserviceversion.yaml, config/manager/env.yaml
We only support the FRR BGP mode d/s,
setting it here as default. This shouldn't
be changed by the users.
Signed-off-by: Ori Braunshtein <obraunsh@redhat.com>
=> Set FRR mode as the default METALLB_BGP_TYPE

manifests/4.10/image-references, manifests/4.10/metallb-operator.v4.10.0.clusterserviceversion.yaml
The manifests were using the upstream frr image.
=> Change the frr image to the openshift one

.github/workflows/general.yml, bindata/deployment/frr/metallb-frr.yaml, bindata/deployment/frr/service-monitors.yaml, bundle/manifests/metallb-operator.clusterserviceversion.yaml, bundle/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, bundle/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml, config/manager/env.yaml, config/metallb_rbac/kube_rbac_proxy.yaml, config/metallb_rbac/kustomization.yaml, controllers/metallb_controller.go, controllers/metallb_controller_test.go, hack/generate-metallb-manifests.sh, hack/kube-rbac-controller.json, hack/kube-rbac-frr.json, hack/kube-rbac-speaker.json, manifests/4.10/metallb-operator.v4.10.0.clusterserviceversion.yaml, manifests/4.10/prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml, manifests/4.10/prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
OpenShift requires metrics to be scraped via https,
this commit adds the ServiceMonitors that enable that.
Depends on https://github.com/metallb/metallb-operator/pull/142
=> Bug 2034410: D/S only: Deploy ServiceMonitors

manifests/4.10/image-references
Kube-rbac-proxy was missing, so ART won't replacing it with the image from brew.
=> Bug 2041483: Add kube-rbac-proxy to image refs

manifests/4.10/metallb-operator.v4.10.0.clusterserviceversion.yaml
remove nodeSelector from clustersvc manifest as it was enforcing the users of metallb CR to configure nodeSelector which is an optional configuration and not mandatory.
=> Bug 2041087: MetalLB CR yaml was enforcing nodeSelector which is an optional config

manifests/4.10/metallb.io_bgppeers.yaml
Add ebgpMulti hop field to OCP 4.10 manifest
=> Bug 2051722: Add ebgpMultihop to OCP 4.10 manifest

manifests/4.11/metallb-operator.v4.11.0.clusterserviceversion.yaml, manifests/stable/metallb-operator.clusterserviceversion.yaml
The speaker is a host networked pod. In order to have its endpoint
reacheable from outside, the exposed (https) ports must be in the
allowed range 9000-9999.
=> Bug 2069705: Pin ports to allowed ranges

bundle/manifests/metallb-operator.clusterserviceversion.yaml, config/samples/kustomization.yaml, config/samples/metallb.io_v1beta1_bfdprofile.yaml, config/samples/metallb.io_v1beta1_ipaddresspool.yaml, config/samples/metallb.io_v1beta2_bgppeer.yaml, config/samples/metallb_v1beta1_bgpadvertisement.yaml, config/samples/metallb_v1beta1_l2advertisement.yaml, manifests/4.11/metallb-operator.v4.11.0.clusterserviceversion.yaml, manifests/stable/metallb-operator.clusterserviceversion.yaml
The alm examples annotation was inadvertently removed while migrating
CRDs, hence adding new versions of bfd profile, bgp peer, ip address
pool, bgp and l2 advertisement examples. This would get webconsole
to get rendered with yaml templates.
Signed-off-by: Periyasamy Palanisamy <pepalani@redhat.com>
=> Bug 2081172: YAML view in webconsole does not show all the available key value pairs of all the objects 

manifests/4.11/metallb-operator.v4.11.0.clusterserviceversion.yaml, manifests/stable/metallb-operator.clusterserviceversion.yaml
We are using frr mode in openshift, the webhooks should be instructed accordingly.
Found this when running metallb's CI.
=> Bug 2081788: CSV: fix the webhook type

manifests/metallb-operator.package.yaml, manifests/stable/image-references, manifests/stable/metallb-operator.clusterserviceversion.yaml
Changing the version of the images as main now is pinned to 4.12.
=> Fix the image versions to stick with 4.12

manifests/4.11/controller_v1_serviceaccount.yaml, manifests/4.11/speaker_v1_serviceaccount.yaml, manifests/stable/controller_v1_serviceaccount.yaml, manifests/stable/speaker_v1_serviceaccount.yaml
Getting the error: Error: Value controller: invalid service account found in bundle.
This service account controller in your bundle is not valid, because a service
account with the same name was already specified in your CSV
=> Bug 2106770: Remove the service account manifests from the bundle

bundleci.Dockerfile
It was still pointing at 4.11. From this change on, the channel is
always going to be stable, so this is the last time this change is
required.
=> Fix the bundleci docker file to refer to stable manifests

bundle/manifests/metallb-operator.clusterserviceversion.yaml
CVP Ops is complaining about the spec missing from metallb:
"error spec does not exist for the custom resource metallb",
trying to fix that.
=> Openshift CVS: Add the spec to metallb

hack/validate_ocp_bundle.sh
Here we add a script that runs operator-sdk bundle validate against our
csv (minus the metadata, taken from upstream).
Signed-off-by: Federico Paolinelli <fpaoline@redhat.com>
=> OCP CI: add a bash script that runs validation against the bundle

manifests/stable/metallb-operator.clusterserviceversion.yaml
This commit would enable validation webhook in the stable manifest csv
for l2advertisment crd as l2adv validation doesn't work on 4.12 deployment.
Signed-off-by: Periyasamy Palanisamy <pepalani@redhat.com>
=> Bug 2100845: Enable webhook for l2advertisement

Makefile, api/v1beta1/bgppeer_types.go, bin/metallb-operator-with-webhooks.yaml, bin/metallb-operator.yaml, bundle/manifests/metallb.io_bgppeers.yaml, config/crd/bases/metallb.io_bgppeers.yaml, manifests/4.10/metallb.io_bgppeers.yaml
FRR supports 4 bytes asns, so we can extend the maximum.
=> OCPBUGS-757: Extend the max asn number to match 4 bytes

manifests/4.11/metallb-operator.v4.11.0.clusterserviceversion.yaml, manifests/stable/metallb-operator.clusterserviceversion.yaml
Fixes the test failure in the CI run https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_metallb/82/pull-ci-openshift-metallb-main-metallb-e2e-metal-ipi-ovn/1567176008472203264
Signed-off-by: Periyasamy Palanisamy <pepalani@redhat.com>
=> Validating webhook for bfdprofile on create

api/v1beta1/addresspool_webhook.go
Verification webhook incorrectly fails when BGP Adv. has only aggregationLengthV6 configured with IPv6 address pools only, because aggregationLength has default of 32 adv.AggregationLength will always be != nil even with ipv6 only config.
Signed-off-by: msherif1234 <mmahmoud@redhat.com>
(cherry picked from commit 279c0301eb65af5c1de34893f852e4856f85ed62)
=> OCPBUGS-5394: Fix invalid verification error when using aggregationLengthV6 only

pkg/helm/config.go, pkg/helm/helm_test.go, pkg/helm/testdata/vanilla-metrics-speaker.golden
Despite reading the environment variable to set the image, we don't use it so the operator always deploy the default one.
=> OCPBUGS-6033: Helm: propagate the rbac image values to the charts

manifests/stable/metallb-operator.clusterserviceversion.yaml
In order for the metallb-operator to be correctly filtered in the OperatorHub for s390x and ppc64le we need to add the correct arch label as supported.
Signed-off-by: Jan Schintag <jan.schintag@de.ibm.com>
=> Add support label for s390x & ppc64le

manifests/4.10/metallb-operator.v4.10.0.clusterserviceversion.yaml
This is tripping the cvp test http://external-ci-coldstorage.datahub.redhat.com/cvp/cvp-redhat-operator-bundle-image-validation-test/ose-metallb-operator-bundle-container-v4.10.0.202302072301.p0.g186cf6b.assembly.stream-1/0898ccd9-df79-487e-aeee-d2cd44ebfe97/operator-metadata-linting-bundle-image-output.txt
gchat thread https://chat.google.com/room/AAAAZrx3KlI/qz4dtG_kSRw
=> OCPBUGS-7315: Fix linting error

bindata/deployment/openshift/metallb-openshift.yaml
Using the host ip is wrong and leads the rbac proxy of the controller to exposing the speaker's metrics if there's a speaker instance running on the node (or not to expose metrics at all otherwise).
=> OCPBUGS-10024: Controller metrics: set the rbac proxy upstream to localhost

manifests/stable/metallb-operator.clusterserviceversion.yaml
As per the official docs, we add the annotation so it's documented that metallb can be mirrored.
https://docs.openshift.com/container-platform/4.11/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-manual-annotations_osdk-generating-csvs
=> Add the "support disconnected" infrastructure annotation

bindata/deployment/openshift/metallb-openshift.yaml
There was an error in the --upstream parameter that prevented the kuberbac proxy to expose the metrics of the controller pod correctly.
=> OCPBUGS-11443: Controller metrics port: fix typo

manifests/4.10/metallb.io_metallbs.yaml
This commit adds the log-level field to the metallb crd in the 4.10 ocp manifests.
=> OCPBUGS-11861: Add log-level to ocp 4.10 manifests

manifests/stable/metallb-operator.clusterserviceversion.yaml
In order to process the extra frr config, the speaker must have read permissions.
=> OCPBUGS-14410: Add permissions to the speaker to read configmaps

bindata/deployment/openshift/metallb-openshift.yaml
This commit fixes a mistake in the implementation of the ml_secret fix for release 4.11, moving
the volumeMount from the FRR container to the speaker container, in the metallb-openshift.yaml file.
=> OCPBUGS-14277: Fix ml_secret volumeMount location

manifests/stable/metallb-operator.clusterserviceversion.yaml
As per the official docs, we add the annotation so it's documented that metallb can be mirrored.
https://docs.openshift.com/container-platform/4.11/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-manual-annotations_osdk-generating-csvs
=> OCPBUGS-11824: Add the "support disconnected" infrastructure annotation

bundle/manifests/manager-account_v1_serviceaccount.yaml
This makes the bundle not valid.
=> OCPBUGS-14830: Remove the service account from the bundle as it's alredy in csv

manifests/stable/manager-account_v1_serviceaccount.yaml
This makes the bundle validation fail
=> OCPBUGS-14830: Remove the service account file from manifests/stable

bindata/deployment/frr/metallb-frr.yaml, bindata/deployment/native/metallb.yaml
This is a backport from release 4.11, bringing the fix for the memberlist secret.
Change the metallb's speaker yamls to mount the memberlist secret into a VolumeMount, and change the METALLB_ML_SECRET_KEY var to METALLB_ML_SECRET_KEY_PATH.
4.11 PRs:
https://github.com/openshift/metallb-operator/pull/162
and
https://github.com/openshift/metallb-operator/pull/165
=> OCPBUGS-14503: [4.10] Change the memberlist secret to contain path

controllers/metallb_controller.go, test/e2e/functional/tests/e2e.go, test/e2e/metallb/metallb.go
This PR cherry-picks 2 commits that fix the metallb controller to print the content of the error in the log, plus
fixing the cleanup order in the e2etests.
This PR references a bug concerning a flaky test case titled:
`Correct and incorrect MetalLB resources coexist should have correct statuses`
=> OCPBUGS-8433: [4.13] Fix metallb controller error log

controllers/metallb_controller.go
This commit brings a fix to the metallb controller that is missing from 4.12, 4.11.
The fix:
The Reason string in Condition object can't be empty and must have atleast one character. so use condition string when it's empty.
=> [release-4.12] OCPBUGS-15771: Fix metallb controller condition reason string

controllers/metallb_controller.go, pkg/status/status.go, test/e2e/functional/tests/e2e.go
cherry-pick of: https://github.com/openshift/metallb-operator/pull/178
Note: 
- The fix for the flake is in the commit: "Use the DeployTimeout const in e2etest".
- The other commits are different improvements that were add together with the fix,
that makes sense to include them here as well.
- The commit "Update kind's node image" was omitted deliberately.
=> [release-4.13] OCPBUGS-8433: Fix flake MetalLB resources should have correct statuses

controllers/metallb_controller.go, pkg/status/status.go, test/e2e/functional/tests/e2e.go
cherry-pick of: #182
Note:
* The fix for the flake is in the commit: "Use the DeployTimeout const in e2etest".
* The other commits are different improvements that were add together with the fix,
that makes sense to include them here as well.
* The commit "Update kind's node image" was omitted deliberately.
=> [release-4.12] OCPBUGS-15771: Fix flake MetalLB resources should have correct statuses

.github/workflows/metallb_e2e.yml, bin/metallb-operator.yaml, bindata/deployment/helm/README.md, bindata/deployment/helm/templates/podmonitor.yaml, bindata/deployment/helm/templates/servicemonitor.yaml, bindata/deployment/helm/templates/speaker.yaml, bindata/deployment/helm/values.schema.json, bindata/deployment/helm/values.yaml, bundle/manifests/metallb-operator.clusterserviceversion.yaml, bundle/manifests/metallb.io_bfdprofiles.yaml, bundle/manifests/metallb.io_bgpadvertisements.yaml, bundle/manifests/metallb.io_bgppeers.yaml, bundle/manifests/metallb.io_ipaddresspools.yaml, bundle/manifests/metallb.io_l2advertisements.yaml, config/crd/bases/metallb.io_bfdprofiles.yaml, config/crd/bases/metallb.io_bgpadvertisements.yaml, config/crd/bases/metallb.io_bgppeers.yaml, config/crd/bases/metallb.io_ipaddresspools.yaml, config/crd/bases/metallb.io_l2advertisements.yaml, config/metallb_rbac/metallb-frr.yaml, config/metallb_rbac/metallb-native.yaml, config/metallb_rbac/metallb-openshift.yaml, controllers/metallb_controller_test.go, hack/common.sh, pkg/helm/testdata/ocp-metrics-speaker.golden, pkg/helm/testdata/vanilla-metrics-speaker.golden
cherry-pick of the relevant commits to bring the liveness probe to 4.12,
the second was not clean, had to manually accept commit refs on `.github/workflows/metallb_e2e.yml` and `hack/common.sh`
depends on https://github.com/openshift/metallb/pull/140 - operator-e2e fails locally using quay.io/openshift/origin-metallb:4.12, passes using a custom build of https://github.com/openshift/metallb/pull/140 (the livez endpoint is missing from 4.12)
=> OCPBUGS-18838: Backport liveness 4.12

hack/ocp_run_e2e.sh
We want to control which tests we run from the metallb operator repo, so it's easier to change a skip contextually to a pr for example.
=> Openshift only: add a e2e test runner file

.snyk
Skipping vendor, e2e tests and tests.
=> OCPBUGS-28364: Add a .snyk configuration file

manifests/stable/metallb-operator.clusterserviceversion.yaml
Adding infra labels as per
https://docs.openshift.com/container-platform/4.15/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-annotations-infra_osdk-generating-csvs
=> OCPBUGS-30738: Openshift CSV: add infra labels

manifests/stable/metallb-operator.clusterserviceversion.yaml
Adding infra labels as per
https://docs.openshift.com/container-platform/4.15/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-annotations-infra_osdk-generating-csvs
=> OCPBUGS-30756: Openshift CSV: add infra labels

manifests/stable/metallb-operator.clusterserviceversion.yaml
The operator is currently pulling the upstream FRR-K8s image while it should consume the d/s one.
=> OCPBUGS-35754: D/S CSV: override the frr-k8s image

manifests/stable/image-references, manifests/stable/metallb-operator.clusterserviceversion.yaml
=> Openshift only: bump the kube rbac proxy image

manifests/stable/metallb-operator.clusterserviceversion.yaml
This PR pins the required SCC to the openshift-metallb-system workload.
Workloads:
1- metallb-operator-webhook-server
2- metallb-operator-controller-manager
**Is this a BUG FIX or a FEATURE ?**:
> Uncomment only one, leave it on its own line:
>
kind bug
> /kind cleanup
> /kind feature
> /kind design
> /kind flake
> /kind failing
> /kind documentation
> /kind regression
**Special notes for your reviewer**:
**Release note**:
```release-note
NONE
```
=> AUTH-482: set required-scc for openshift workloads

bundle.Dockerfile, manifests/metallb-operator.package.yaml, manifests/ocpcsv/align.sh, manifests/ocpcsv/bases/metallb-operator.clusterserviceversion.yaml, manifests/ocpcsv/controller-webhook-patch.yaml, manifests/ocpcsv/ocpvariables.yaml, manifests/stable/image-references, manifests/stable/metallb-operator.clusterserviceversion.yaml
Aligning the csv and the images versions to 4.18.
=> OCPBUGS-41937: Align the versions to 4.18

manifests/stable/metallb-operator.clusterserviceversion.yaml
**Is this a BUG FIX or a FEATURE ?**:
This PR pins the required SCC to the openshift-metallb-system workload.
Workloads:
1- metallb-operator-webhook-server
2- metallb-operator-controller-manager
> Uncomment only one, leave it on its own line:
kind bug
> /kind cleanup
> /kind feature
> /kind design
> /kind flake
> /kind failing
> /kind documentation
> /kind regression
**Special notes for your reviewer**:
**Release note**:
```release-note
NONE
```
=> [release-4.16] OCPBUGS-41805: set required-scc for openshift workloads

manifests/stable/metallb-operator.clusterserviceversion.yaml
The api is now available, let's flip frrk8s via CNO as the default (and only) deployment mechanism for frr-k8s.
=> Deploy frr-k8s via CNO by default

manifests/stable/metallb-operator.clusterserviceversion.yaml
Fix CSV validation by ART, currently failing with:
```
Bundle ose-metallb-operator-bundle-container-v4.19.0.202502102307.p0.g6a06990.assembly.stream.el9-2
CSV metadata.name has no datestamp: metallb-operator.v4.18.0
Bundle ose-metallb-operator-bundle-container-v4.19.0.202502102307.p0.g6a06990.assembly.stream.el9-2
CSV spec.version has no datestamp: 4.18.0
```
=> NO-JIRA: Fix 4.19 CSV references

manifests/stable/metallb.io_bgppeers.yaml
The CRD changes were brought to 4.17 without updating the stable manifests.
should have been part of https://github.com/openshift/metallb-operator/pull/265
=> OCPBUGS-55021: [4.17] OpenShift only: sync stable manifests with dynamicASN

bundle.Dockerfile, manifests/metallb-operator.package.yaml, manifests/ocpcsv/align.sh, manifests/ocpcsv/bases/metallb-operator.clusterserviceversion.yaml, manifests/ocpcsv/controller-webhook-patch.yaml, manifests/ocpcsv/ocpvariables.yaml, manifests/stable/image-references, manifests/stable/metallb-operator.clusterserviceversion.yaml
**Is this a BUG FIX or a FEATURE ?**:
/kind bug
/kind cleanup
This PR updates manifest references to `4.19`
**Release note**:
```release-note
NA
```
=> OCPBUGS-60378: [release-4.19] Align manifests to 4.19 to fix the failing operator-e2e job

go.mod, go.sum, vendor/github.com/golang/glog/glog.go, vendor/github.com/golang/glog/glog_file.go, vendor/github.com/golang/glog/glog_file_nonwindows.go, vendor/github.com/golang/glog/glog_file_windows.go, vendor/modules.txt
To addresses the CVE-2024-45339 this PR bumps `github.com/golang/glog` from `v1.2.1` to `v1.2.4`
=> OCPBUGS-58841: [release-4.19] Bump github.com/golang/glog to v1.2.4

go.mod, go.sum, vendor/github.com/golang/glog/glog.go, vendor/github.com/golang/glog/glog_file.go, vendor/github.com/golang/glog/glog_file_nonwindows.go, vendor/github.com/golang/glog/glog_file_windows.go, vendor/modules.txt
To addresses the CVE-2024-45339 this PR bumps `github.com/golang/glog` from `v1.2.1` to `v1.2.4`
=> OCPBUGS-58625: [release-4.18] Bump github.com/golang/glog to v1.2.4
